apiVersion: apps/v1
kind: Deployment
metadata:
  name: skit-app-deployment
spec:
  selector:
    matchLabels:
      app: skit-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: skit-app
    spec:
      containers:
      - name: skit-app
        image: pradeep34946/skit:V1
        ports:
        - containerPort: 80